"""
Controller function index for this Sensio installation.

Auto-generated from smarthome.bash (supplier-provided script).
Each entry: (internal_name, display_name).

Usage:
    from sensio.functions import FUNCTIONS, find_function
    fn = find_function("kitchen light on")
    # fn -> ("B_LightKjkkenStue_ON", "Kjøkken/Stue Light On")
"""

from __future__ import annotations
from typing import Optional


# (internal_name, display_name) -- index matches bash script ordering
FUNCTIONS: list[tuple[str, str]] = [
    ("B_Vaskerom0533_St1_Dec", "Vaskerom Temperature Dec State1"),
    ("B_Vaskerom0533_St2_Dec", "Vaskerom Temperature Dec State2"),
    ("B_Vaskerom0533_St3_Dec", "Vaskerom Temperature Dec State3"),
    ("B_Vaskerom0533_Temp_Dec", "Vaskerom Temperature Dec"),
    ("B_Vaskerom0533_Save", "Vaskerom Temperature Scene Save"),
    ("B_Vaskerom0533_Sc1", "Vaskerom Temperature Scene 1"),
    ("B_Vaskerom0533_Sc2", "Vaskerom Temperature Scene 2"),
    ("B_Vaskerom0533_Sc3", "Vaskerom Temperature Scene 3"),
    ("B_Vaskerom0533_St1_Inc", "Vaskerom Temperature Inc State1"),
    ("B_Vaskerom0533_St2_Inc", "Vaskerom Temperature Inc State2"),
    ("B_Vaskerom0533_St3_Inc", "Vaskerom Temperature Inc State3"),
    ("B_Vaskerom0533_Temp_Inc", "Vaskerom Temperature Inc"),
    ("B_VaskeromMode_Away", "Vaskerom Away Mode"),
    ("B_VaskeromMode_In", "Vaskerom Day Mode"),
    ("B_VaskeromMode_Night", "Vaskerom Night Mode"),
    ("B_VaskeromMode_Vacation", "Vaskerom Vacation Mode"),
    ("B_Vaskerom0533_Set", "Vaskerom Temperature Set"),
    ("B_LightUtelys_OFF", "Utelys Light Off"),
    ("B_LightUtelys_ON", "Utelys Light On"),
    ("B_LightUtelys_Save", "Utelys Light Save"),
    ("B_LightUtelys_SaveSc1", "Utelys Light Save Sc1"),
    ("B_LightUtelys_SaveSc2", "Utelys Light Save Sc2"),
    ("B_LightUtelys_SaveSc3", "Utelys Light Save Sc3"),
    ("B_LightUtelys_SaveSc4", "Utelys Light Save Sc4"),
    ("B_LightUtelys_Sc1", "Utelys Light Scene 1"),
    ("B_LightUtelys_Sc2", "Utelys Light Scene 2"),
    ("B_LightUtelys_Sc3", "Utelys Light Scene 3"),
    ("B_LightUtelys_Sc4", "Utelys Light Scene 4"),
    ("B_LightUtelys_ToggleOn", "Utelys Light On Toggle"),
    ("B_UtelysMode_Away", "Utelys Away Mode"),
    ("B_UtelysMode_In", "Utelys Day Mode"),
    ("B_UtelysMode_Night", "Utelys Night Mode"),
    ("B_UtelysMode_Vacation", "Utelys Vacation Mode"),
    ("B_R_UtelysUtelys_OFF", "UtelysOff"),
    ("B_R_UtelysUtelys_ON", "UtelysOn"),
    ("B_LightKjkkenStue_OFF", "Kjøkken/Stue Light Off"),
    ("B_LightKjkkenStue_ON", "Kjøkken/Stue Light On"),
    ("B_LightKjkkenStue_Save", "Kjøkken/Stue Light Save"),
    ("B_LightKjkkenStue_SaveSc1", "Kjøkken/Stue Light Save Sc1"),
    ("B_LightKjkkenStue_SaveSc2", "Kjøkken/Stue Light Save Sc2"),
    ("B_LightKjkkenStue_SaveSc3", "Kjøkken/Stue Light Save Sc3"),
    ("B_LightKjkkenStue_SaveSc4", "Kjøkken/Stue Light Save Sc4"),
    ("B_LightKjkkenStue_Sc1", "Kjøkken/Stue Light Scene 1"),
    ("B_LightKjkkenStue_Sc2", "Kjøkken/Stue Light Scene 2"),
    ("B_LightKjkkenStue_Sc3", "Kjøkken/Stue Light Scene 3"),
    ("B_LightKjkkenStue_Sc4", "Kjøkken/Stue Light Scene 4"),
    ("B_LightKjkkenStue_ToggleOn", "Kjøkken/Stue Light On Toggle"),
    ("B_KjkkenStueMode_Away", "Kjøkken/Stue Away Mode"),
    ("B_KjkkenStueMode_In", "Kjøkken/Stue Day Mode"),
    ("B_KjkkenStueMode_Night", "Kjøkken/Stue Night Mode"),
    ("B_KjkkenStueMode_Vacation", "Kjøkken/Stue Vacation Mode"),
    ("B_D_SpotlightsKjkkenKjkkenStu", "Spotlights KjøkkenSet"),
    ("B_D_KjkkenyKjkkenStue_SET", "KjøkkenøySet"),
    ("B_D_SpotlightsSpisKjkkenStue_", "Spotlights SpisSet"),
    ("B_D_StikkoVinduKjkkenStue_SET", "Stikk. o/VinduSet"),
    ("B_D_SpotlightsStueKjkkenStue_", "Spotlights StueSet"),
    ("B_LightTVStue_OFF", "TV-Stue Light Off"),
    ("B_LightTVStue_ON", "TV-Stue Light On"),
    ("B_LightTVStue_Save", "TV-Stue Light Save"),
    ("B_LightTVStue_SaveSc1", "TV-Stue Light Save Sc1"),
    ("B_LightTVStue_SaveSc2", "TV-Stue Light Save Sc2"),
    ("B_LightTVStue_SaveSc3", "TV-Stue Light Save Sc3"),
    ("B_LightTVStue_SaveSc4", "TV-Stue Light Save Sc4"),
    ("B_LightTVStue_Sc1", "TV-Stue Light Scene 1"),
    ("B_LightTVStue_Sc2", "TV-Stue Light Scene 2"),
    ("B_LightTVStue_Sc3", "TV-Stue Light Scene 3"),
    ("B_LightTVStue_Sc4", "TV-Stue Light Scene 4"),
    ("B_LightTVStue_ToggleOn", "TV-Stue Light On Toggle"),
    ("B_TVStueMode_Away", "TV-Stue Away Mode"),
    ("B_TVStueMode_In", "TV-Stue Day Mode"),
    ("B_TVStueMode_Night", "TV-Stue Night Mode"),
    ("B_TVStueMode_Vacation", "TV-Stue Vacation Mode"),
    ("B_D_SpotlightsTVStueTVStue_SET", "Spotlights TV StueSet"),
    ("B_TempHus_Sc1", "Hus Temperature Scene 1"),
    ("B_TempHus_Sc2", "Hus Temperature Scene 2"),
    ("B_TempHus_Sc3", "Hus Temperature Scene 3"),
    ("B_HouseMode_Away", "House Away Scene"),
    ("B_HouseMode_In", "House In Scene"),
    ("B_HouseMode_Night", "House Night Scene"),
    ("B_HouseMode_Vacation", "House Vacation Scene"),
    ("B_LightHus_OFF", "Hus Light Off"),
    ("B_LightHus_ON", "Hus Light On"),
    ("B_LightHus_Save", "Hus Light Save"),
    ("B_LightHus_SaveSc1", "Hus Light Save Sc1"),
    ("B_LightHus_SaveSc2", "Hus Light Save Sc2"),
    ("B_LightHus_SaveSc3", "Hus Light Save Sc3"),
    ("B_LightHus_SaveSc4", "Hus Light Save Sc4"),
    ("B_LightHus_Sc1", "Hus Light Scene 1"),
    ("B_LightHus_Sc2", "Hus Light Scene 2"),
    ("B_LightHus_Sc3", "Hus Light Scene 3"),
    ("B_LightHus_Sc4", "Hus Light Scene 4"),
    ("B_LightHus_ToggleOn", "Hus Light On Toggle"),
    ("B_AllAlarms_RESET", "Reset All Alarms"),
    ("B_HallTrappEntre0593_St1_Dec", "Hall/Trapp/Entre Temperature Dec State1"),
    ("B_HallTrappEntre0593_St2_Dec", "Hall/Trapp/Entre Temperature Dec State2"),
    ("B_HallTrappEntre0593_St3_Dec", "Hall/Trapp/Entre Temperature Dec State3"),
    ("B_HallTrappEntre0593_Temp_Dec", "Hall/Trapp/Entre Temperature Dec"),
    ("B_HallTrappEntre0593_Save", "Hall/Trapp/Entre Temperature Scene Save"),
    ("B_HallTrappEntre0593_Sc1", "Hall/Trapp/Entre Temperature Scene 1"),
    ("B_HallTrappEntre0593_Sc2", "Hall/Trapp/Entre Temperature Scene 2"),
    ("B_HallTrappEntre0593_Sc3", "Hall/Trapp/Entre Temperature Scene 3"),
    ("B_HallTrappEntre0593_St1_Inc", "Hall/Trapp/Entre Temperature Inc State1"),
    ("B_HallTrappEntre0593_St2_Inc", "Hall/Trapp/Entre Temperature Inc State2"),
    ("B_HallTrappEntre0593_St3_Inc", "Hall/Trapp/Entre Temperature Inc State3"),
    ("B_HallTrappEntre0593_Temp_Inc", "Hall/Trapp/Entre Temperature Inc"),
    ("B_LightHallTrappEntre_OFF", "Hall/Trapp/Entre Light Off"),
    ("B_LightHallTrappEntre_ON", "Hall/Trapp/Entre Light On"),
    ("B_LightHallTrappEntre_Save", "Hall/Trapp/Entre Light Save"),
    ("B_LightHallTrappEntre_SaveSc1", "Hall/Trapp/Entre Light Save Sc1"),
    ("B_LightHallTrappEntre_SaveSc2", "Hall/Trapp/Entre Light Save Sc2"),
    ("B_LightHallTrappEntre_SaveSc3", "Hall/Trapp/Entre Light Save Sc3"),
    ("B_LightHallTrappEntre_SaveSc4", "Hall/Trapp/Entre Light Save Sc4"),
    ("B_LightHallTrappEntre_Sc1", "Hall/Trapp/Entre Light Scene 1"),
    ("B_LightHallTrappEntre_Sc2", "Hall/Trapp/Entre Light Scene 2"),
    ("B_LightHallTrappEntre_Sc3", "Hall/Trapp/Entre Light Scene 3"),
    ("B_LightHallTrappEntre_Sc4", "Hall/Trapp/Entre Light Scene 4"),
    ("B_LightHallTrappEntre_ToggleOn", "Hall/Trapp/Entre Light On Toggle"),
    ("B_HallTrappEntreMode_Away", "Hall/Trapp/Entre Away Mode"),
    ("B_HallTrappEntreMode_In", "Hall/Trapp/Entre Day Mode"),
    ("B_HallTrappEntreMode_Night", "Hall/Trapp/Entre Night Mode"),
    ("B_HallTrappEntreMode_Vacation", "Hall/Trapp/Entre Vacation Mode"),
    ("B_HallTrappEntre0593_Set", "Hall/Trapp/Entre Temperature Set"),
    ("B_D_Trapp2etgHallTrappEntre_S", "Trapp 2etg.Set"),
    ("B_D_Hall2etgHallTrappEntre_SET", "Hall 2etg.Set"),
    ("B_Gang1etg0573_St1_Dec", "Gang 1etg. Temperature Dec State1"),
    ("B_Gang1etg0573_St2_Dec", "Gang 1etg. Temperature Dec State2"),
    ("B_Gang1etg0573_St3_Dec", "Gang 1etg. Temperature Dec State3"),
    ("B_Gang1etg0573_Temp_Dec", "Gang 1etg. Temperature Dec"),
    ("B_Gang1etg0573_Save", "Gang 1etg. Temperature Scene Save"),
    ("B_Gang1etg0573_Sc1", "Gang 1etg. Temperature Scene 1"),
    ("B_Gang1etg0573_Sc2", "Gang 1etg. Temperature Scene 2"),
    ("B_Gang1etg0573_Sc3", "Gang 1etg. Temperature Scene 3"),
    ("B_Gang1etg0573_St1_Inc", "Gang 1etg. Temperature Inc State1"),
    ("B_Gang1etg0573_St2_Inc", "Gang 1etg. Temperature Inc State2"),
    ("B_Gang1etg0573_St3_Inc", "Gang 1etg. Temperature Inc State3"),
    ("B_Gang1etg0573_Temp_Inc", "Gang 1etg. Temperature Inc"),
    ("B_LightGang1etg_OFF", "Gang 1etg. Light Off"),
    ("B_LightGang1etg_ON", "Gang 1etg. Light On"),
    ("B_LightGang1etg_Save", "Gang 1etg. Light Save"),
    ("B_LightGang1etg_SaveSc1", "Gang 1etg. Light Save Sc1"),
    ("B_LightGang1etg_SaveSc2", "Gang 1etg. Light Save Sc2"),
    ("B_LightGang1etg_SaveSc3", "Gang 1etg. Light Save Sc3"),
    ("B_LightGang1etg_SaveSc4", "Gang 1etg. Light Save Sc4"),
    ("B_LightGang1etg_Sc1", "Gang 1etg. Light Scene 1"),
    ("B_LightGang1etg_Sc2", "Gang 1etg. Light Scene 2"),
    ("B_LightGang1etg_Sc3", "Gang 1etg. Light Scene 3"),
    ("B_LightGang1etg_Sc4", "Gang 1etg. Light Scene 4"),
    ("B_LightGang1etg_ToggleOn", "Gang 1etg. Light On Toggle"),
    ("B_Gang1etgMode_Away", "Gang 1etg. Away Mode"),
    ("B_Gang1etgMode_In", "Gang 1etg. Day Mode"),
    ("B_Gang1etgMode_Night", "Gang 1etg. Night Mode"),
    ("B_Gang1etgMode_Vacation", "Gang 1etg. Vacation Mode"),
    ("B_Gang1etg0573_Set", "Gang 1etg. Temperature Set"),
    ("B_D_Gang1etgGang1etg_SET", "Gang 1etgSet"),
    ("B_Kjellerstue061_CHECK", "Kjellerstue Check Min Max"),
    ("B_Kjellerstue061_St1_Dec", "Kjellerstue Temperature Dec State1"),
    ("B_Kjellerstue061_St2_Dec", "Kjellerstue Temperature Dec State2"),
    ("B_Kjellerstue061_St3_Dec", "Kjellerstue Temperature Dec State3"),
    ("B_Kjellerstue061_Temp_Dec", "Kjellerstue Temperature Dec"),
    ("B_Kjellerstue061_Save", "Kjellerstue Temperature Scene Save"),
    ("B_Kjellerstue061_Sc1", "Kjellerstue Temperature Scene 1"),
    ("B_Kjellerstue061_Sc2", "Kjellerstue Temperature Scene 2"),
    ("B_Kjellerstue061_Sc3", "Kjellerstue Temperature Scene 3"),
    ("B_Kjellerstue061_St1_Inc", "Kjellerstue Temperature Inc State1"),
    ("B_Kjellerstue061_St2_Inc", "Kjellerstue Temperature Inc State2"),
    ("B_Kjellerstue061_St3_Inc", "Kjellerstue Temperature Inc State3"),
    ("B_Kjellerstue061_Temp_Inc", "Kjellerstue Temperature Inc"),
    ("B_LightKjellerstue_OFF", "Kjellerstue Light Off"),
    ("B_LightKjellerstue_ON", "Kjellerstue Light On"),
    ("B_LightKjellerstue_Save", "Kjellerstue Light Save"),
    ("B_LightKjellerstue_SaveSc1", "Kjellerstue Light Save Sc1"),
    ("B_LightKjellerstue_SaveSc2", "Kjellerstue Light Save Sc2"),
    ("B_LightKjellerstue_SaveSc3", "Kjellerstue Light Save Sc3"),
    ("B_LightKjellerstue_SaveSc4", "Kjellerstue Light Save Sc4"),
    ("B_LightKjellerstue_Sc1", "Kjellerstue Light Scene 1"),
    ("B_LightKjellerstue_Sc2", "Kjellerstue Light Scene 2"),
    ("B_LightKjellerstue_Sc3", "Kjellerstue Light Scene 3"),
    ("B_LightKjellerstue_Sc4", "Kjellerstue Light Scene 4"),
    ("B_LightKjellerstue_ToggleOn", "Kjellerstue Light On Toggle"),
    ("B_KjellerstueMode_Away", "Kjellerstue Away Mode"),
    ("B_KjellerstueMode_In", "Kjellerstue Day Mode"),
    ("B_KjellerstueMode_Night", "Kjellerstue Night Mode"),
    ("B_KjellerstueMode_Vacation", "Kjellerstue Vacation Mode"),
    ("B_Kjellerstue061_Set", "Kjellerstue Temperature Set"),
    ("B_D_KjellerstueKjellerstue_SET", "KjellerstueSet"),
    ("B_Bad2etg0513_St1_Dec", "Bad 2etg. Temperature Dec State1"),
    ("B_Bad2etg0513_St2_Dec", "Bad 2etg. Temperature Dec State2"),
    ("B_Bad2etg0513_St3_Dec", "Bad 2etg. Temperature Dec State3"),
    ("B_Bad2etg0513_Temp_Dec", "Bad 2etg. Temperature Dec"),
    ("B_Bad2etg0513_Save", "Bad 2etg. Temperature Scene Save"),
    ("B_Bad2etg0513_Sc1", "Bad 2etg. Temperature Scene 1"),
    ("B_Bad2etg0513_Sc2", "Bad 2etg. Temperature Scene 2"),
    ("B_Bad2etg0513_Sc3", "Bad 2etg. Temperature Scene 3"),
    ("B_Bad2etg0513_St1_Inc", "Bad 2etg. Temperature Inc State1"),
    ("B_Bad2etg0513_St2_Inc", "Bad 2etg. Temperature Inc State2"),
    ("B_Bad2etg0513_St3_Inc", "Bad 2etg. Temperature Inc State3"),
    ("B_Bad2etg0513_Temp_Inc", "Bad 2etg. Temperature Inc"),
    ("B_LightBad2etg_OFF", "Bad 2etg. Light Off"),
    ("B_LightBad2etg_ON", "Bad 2etg. Light On"),
    ("B_LightBad2etg_Save", "Bad 2etg. Light Save"),
    ("B_LightBad2etg_SaveSc1", "Bad 2etg. Light Save Sc1"),
    ("B_LightBad2etg_SaveSc2", "Bad 2etg. Light Save Sc2"),
    ("B_LightBad2etg_SaveSc3", "Bad 2etg. Light Save Sc3"),
    ("B_LightBad2etg_SaveSc4", "Bad 2etg. Light Save Sc4"),
    ("B_LightBad2etg_Sc1", "Bad 2etg. Light Scene 1"),
    ("B_LightBad2etg_Sc2", "Bad 2etg. Light Scene 2"),
    ("B_LightBad2etg_Sc3", "Bad 2etg. Light Scene 3"),
    ("B_LightBad2etg_Sc4", "Bad 2etg. Light Scene 4"),
    ("B_LightBad2etg_ToggleOn", "Bad 2etg. Light On Toggle"),
    ("B_Bad2etgMode_Away", "Bad 2etg. Away Mode"),
    ("B_Bad2etgMode_In", "Bad 2etg. Day Mode"),
    ("B_Bad2etgMode_Night", "Bad 2etg. Night Mode"),
    ("B_Bad2etgMode_Vacation", "Bad 2etg. Vacation Mode"),
    ("B_Bad2etg0513_Set", "Bad 2etg. Temperature Set"),
    ("B_D_Bad2etgBad2etg_SET", "Bad 2etg.Set"),
    ("B_Badst1etg0633_St1_Dec", "Bad Øst 1etg. Temperature Dec State1"),
    ("B_Badst1etg0633_St2_Dec", "Bad Øst 1etg. Temperature Dec State2"),
    ("B_Badst1etg0633_St3_Dec", "Bad Øst 1etg. Temperature Dec State3"),
    ("B_Badst1etg0633_Temp_Dec", "Bad Øst 1etg. Temperature Dec"),
    ("B_Badst1etg0633_Save", "Bad Øst 1etg. Temperature Scene Save"),
    ("B_Badst1etg0633_Sc1", "Bad Øst 1etg. Temperature Scene 1"),
    ("B_Badst1etg0633_Sc2", "Bad Øst 1etg. Temperature Scene 2"),
    ("B_Badst1etg0633_Sc3", "Bad Øst 1etg. Temperature Scene 3"),
    ("B_Badst1etg0633_St1_Inc", "Bad Øst 1etg. Temperature Inc State1"),
    ("B_Badst1etg0633_St2_Inc", "Bad Øst 1etg. Temperature Inc State2"),
    ("B_Badst1etg0633_St3_Inc", "Bad Øst 1etg. Temperature Inc State3"),
    ("B_Badst1etg0633_Temp_Inc", "Bad Øst 1etg. Temperature Inc"),
    ("B_LightBadst1etg_OFF", "Bad Øst 1etg. Light Off"),
    ("B_LightBadst1etg_ON", "Bad Øst 1etg. Light On"),
    ("B_LightBadst1etg_Save", "Bad Øst 1etg. Light Save"),
    ("B_LightBadst1etg_SaveSc1", "Bad Øst 1etg. Light Save Sc1"),
    ("B_LightBadst1etg_SaveSc2", "Bad Øst 1etg. Light Save Sc2"),
    ("B_LightBadst1etg_SaveSc3", "Bad Øst 1etg. Light Save Sc3"),
    ("B_LightBadst1etg_SaveSc4", "Bad Øst 1etg. Light Save Sc4"),
    ("B_LightBadst1etg_Sc1", "Bad Øst 1etg. Light Scene 1"),
    ("B_LightBadst1etg_Sc2", "Bad Øst 1etg. Light Scene 2"),
    ("B_LightBadst1etg_Sc3", "Bad Øst 1etg. Light Scene 3"),
    ("B_LightBadst1etg_Sc4", "Bad Øst 1etg. Light Scene 4"),
    ("B_LightBadst1etg_ToggleOn", "Bad Øst 1etg. Light On Toggle"),
    ("B_Badst1etgMode_Away", "Bad Øst 1etg. Away Mode"),
    ("B_Badst1etgMode_In", "Bad Øst 1etg. Day Mode"),
    ("B_Badst1etgMode_Night", "Bad Øst 1etg. Night Mode"),
    ("B_Badst1etgMode_Vacation", "Bad Øst 1etg. Vacation Mode"),
    ("B_Badst1etg0633_Set", "Bad Øst 1etg. Temperature Set"),
    ("B_D_Badst1etgBadst1etg_SET", "Bad Øst1etg.Set"),
    ("B_LightSovSovWCmm_OFF", "Sov, Sov, WC m.m. Light Off"),
    ("B_LightSovSovWCmm_ON", "Sov, Sov, WC m.m. Light On"),
    ("B_LightSovSovWCmm_Save", "Sov, Sov, WC m.m. Light Save"),
    ("B_LightSovSovWCmm_SaveSc1", "Sov, Sov, WC m.m. Light Save Sc1"),
    ("B_LightSovSovWCmm_SaveSc2", "Sov, Sov, WC m.m. Light Save Sc2"),
    ("B_LightSovSovWCmm_SaveSc3", "Sov, Sov, WC m.m. Light Save Sc3"),
    ("B_LightSovSovWCmm_SaveSc4", "Sov, Sov, WC m.m. Light Save Sc4"),
    ("B_LightSovSovWCmm_Sc1", "Sov, Sov, WC m.m. Light Scene 1"),
    ("B_LightSovSovWCmm_Sc2", "Sov, Sov, WC m.m. Light Scene 2"),
    ("B_LightSovSovWCmm_Sc3", "Sov, Sov, WC m.m. Light Scene 3"),
    ("B_LightSovSovWCmm_Sc4", "Sov, Sov, WC m.m. Light Scene 4"),
    ("B_LightSovSovWCmm_ToggleOn", "Sov, Sov, WC m.m. Light On Toggle"),
    ("B_SovSovWCmmMode_Away", "Sov, Sov, WC m.m. Away Mode"),
    ("B_SovSovWCmmMode_In", "Sov, Sov, WC m.m. Day Mode"),
    ("B_SovSovWCmmMode_Night", "Sov, Sov, WC m.m. Night Mode"),
    ("B_SovSovWCmmMode_Vacation", "Sov, Sov, WC m.m. Vacation Mode"),
    ("B_R_PAvSovWCmmSovSovWCmm_OFF", "På/Av Sov, WC m.m.Off"),
    ("B_R_PAvSovWCmmSovSovWCmm_ON", "På/Av Sov, WC m.m.On"),
    ("B_BadVest1etg0553_St1_Dec", "Bad Vest 1etg. Temperature Dec State1"),
    ("B_BadVest1etg0553_St2_Dec", "Bad Vest 1etg. Temperature Dec State2"),
    ("B_BadVest1etg0553_St3_Dec", "Bad Vest 1etg. Temperature Dec State3"),
    ("B_BadVest1etg0553_Temp_Dec", "Bad Vest 1etg. Temperature Dec"),
    ("B_BadVest1etg0553_Save", "Bad Vest 1etg. Temperature Scene Save"),
    ("B_BadVest1etg0553_Sc1", "Bad Vest 1etg. Temperature Scene 1"),
    ("B_BadVest1etg0553_Sc2", "Bad Vest 1etg. Temperature Scene 2"),
    ("B_BadVest1etg0553_Sc3", "Bad Vest 1etg. Temperature Scene 3"),
    ("B_BadVest1etg0553_St1_Inc", "Bad Vest 1etg. Temperature Inc State1"),
    ("B_BadVest1etg0553_St2_Inc", "Bad Vest 1etg. Temperature Inc State2"),
    ("B_BadVest1etg0553_St3_Inc", "Bad Vest 1etg. Temperature Inc State3"),
    ("B_BadVest1etg0553_Temp_Inc", "Bad Vest 1etg. Temperature Inc"),
    ("B_BadVest1etgMode_Away", "Bad Vest 1etg. Away Mode"),
    ("B_BadVest1etgMode_In", "Bad Vest 1etg. Day Mode"),
    ("B_BadVest1etgMode_Night", "Bad Vest 1etg. Night Mode"),
    ("B_BadVest1etgMode_Vacation", "Bad Vest 1etg. Vacation Mode"),
    ("B_BadVest1etg0553_Set", "Bad Vest 1etg. Temperature Set"),
]

# Lookup by display name (case-insensitive)
FUNCTIONS_BY_NAME: dict[str, str] = {
    label.lower(): func for func, label in FUNCTIONS
}


def find_function(query: str) -> Optional[tuple[str, str]]:
    """Find a function by display name or internal name (case-insensitive, partial match).

    Returns (func_name, display_name) or None.
    Tries exact display-name match first, then partial match on both name fields.
    """
    q = query.lower()
    # Exact display-name match
    if q in FUNCTIONS_BY_NAME:
        func = FUNCTIONS_BY_NAME[q]
        label = next(lbl for fn, lbl in FUNCTIONS if fn == func)
        return (func, label)
    # Partial match on display name or internal name
    for func, label in FUNCTIONS:
        if q in label.lower() or q in func.lower():
            return (func, label)
    return None
